// Generated by scripts/studio/build-runtime-vendor.mjs. The sha256 of the committed
// public/studio-runtime/v1/vendor.js. Pinned: v1 never changes (rule 8.7).
export const VENDOR_V1_SHA256 = '1ff14b349e3a46ba9461dfb5bffaea43ec78c6c4e4a4cfaa859b8d1eed981618'
