// Generated by scripts/studio/build-runtime-vendor.mjs. The sha256 of each committed
// public/studio-runtime/<version>/vendor.js. Pinned: a released version never changes
// (rule 8.7).
export const VENDOR_V1_SHA256 = '1ff14b349e3a46ba9461dfb5bffaea43ec78c6c4e4a4cfaa859b8d1eed981618'
export const VENDOR_V2_SHA256 = 'b10ad6c27c1ce974ca26339de405a687abe1668f551efccc678b22b580b480a2'
