// Shared module/PDF fixture — a REALISTIC spread of modules, dividers and items for one
// course section. Used by both the canonical intern seed (seed-dev.ts) and the standalone
// seed-modules-tile-fixtures.ts (which targets an arbitrary section for UI dev work).
//
// The fixture is deliberately awkward, not tidy. It includes the cases that break layouts:
//   - rows of 2, 3 and 4 modules (dividers end a row, so row length varies)
//   - a very long filename + a long description, to find truncation/clamping
//   - a module with NO items (the "Empty" summary and the empty-panel copy)
//   - a module with no week_number (the tile has no eyebrow to align to)
//   - a module holding an in-module section_divider item (full width inside the panel)
//   - two locked weeks, whose items must never reach the browser
//
// PDF lecture items point at REAL, genuinely multi-page objects in the course-materials
// bucket (generated by fixtures/pdf.ts — a real syllabus and a real set of lecture notes,
// both 3 real pages, uploaded once and shared). This matters for more than the viewer: a
// row with no file isn't openable, so StudentModuleItemRow renders it as a div rather
// than a button — deliberately, see its header — and it never becomes a tab stop. It also
// means the displayed page count is TRUE — earlier this fixture reused a 1-page test file
// with a fabricated page-count label, which read as a bug the first time someone opened
// one (a module claiming "47 pages" that opened to 1).
//
// Decks, notes and dividers deliberately keep NO file: a deck whose upload never happened
// is a real state worth seeing, and pointing a `.ppt` row at PDF bytes would make the
// viewer look broken for the wrong reason.
//
// Idempotent: every row has a deterministic uuid derived from its slug, so a re-run
// replaces this fixture's own rows and leaves anything built by hand untouched.

import { type SupabaseClient } from '@supabase/supabase-js'
import { v5 as uuidv5 } from 'uuid'
import { generateLectureNotes, generateSyllabus } from './pdf'

const NS = uuidv5('scholera-dev-modules-tile-fixtures', uuidv5.DNS)
// Scoped by section: two sections seeding this same fixture must get independent rows,
// not collide on one shared id and steal each other's modules (bug caught in testing —
// unscoped ids meant seeding a second section MOVED the rows instead of copying them).
const idFor = (sectionId: string, slug: string) => uuidv5(`${sectionId}:${slug}`, NS)

const days = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString()

// ── The shared sample files ───────────────────────────────────────────

/* Generated once at import time — real, multi-page PDFs (see fixtures/pdf.ts), not a
   fabricated page count on a reused 1-page test file. Paths are deliberately NOT under a
   section id: this is shared fixture data, and nothing in the read path cares
   (signModuleItemContent signs whatever filePath it is given). */
export const SYLLABUS_PDF_PATH = 'dev-fixtures/course-materials/cs101-syllabus.pdf'
export const LECTURE_NOTES_PDF_PATH = 'dev-fixtures/course-materials/lecture-notes.pdf'
const SYLLABUS = generateSyllabus()
const LECTURE_NOTES = generateLectureNotes()
const BUCKET = 'course-materials'

// ── Content builders (shapes from src/lib/validations/module.ts) ──────

/* `variant` picks which real generated PDF the row points at. fileSize and pageCount are
   read off the actual bytes/pages, so what the module list shows always matches what
   opening the file shows. */
const pdf = (variant: 'syllabus' | 'notes', fileName: string) => {
  const source = variant === 'syllabus' ? SYLLABUS : LECTURE_NOTES
  const filePath = variant === 'syllabus' ? SYLLABUS_PDF_PATH : LECTURE_NOTES_PDF_PATH
  return {
    fileType: 'pdf',
    fileName,
    fileSize: String(source.bytes.length),
    /* A real object, so the row is openable → a button, a tab stop, and the viewer and
       download both work. The displayed fileName is free to differ from the stored
       object's name; that is exactly how the real upload path behaves. */
    filePath,
    extraction: { status: 'completed', metadata: { pageCount: source.pageCount } },
  }
}
const deck = (fileName: string, mb = 8.2) => ({
  fileType: 'ppt',
  fileName,
  fileSize: String(Math.round(mb * 1_000_000)),
})
const video = (videoUrl: string, minutes: number) => ({
  videoUrl,
  provider: 'youtube',
  duration: minutes,
})
const note = (body: string) => ({ body })
const paper = (url: string, venue: string, venueId: string) => ({
  url,
  referenceType: 'paper',
  venue,
  venueId,
})

// ── The fixture ──────────────────────────────────────────────────────

type Item = {
  slug: string
  type: 'lecture' | 'video' | 'note' | 'reference' | 'section_divider'
  title: string
  description?: string
  content: Record<string, unknown>
}
type Entry =
  | { kind: 'divider'; slug: string; title: string }
  | {
      kind: 'module'
      slug: string
      title: string
      description?: string
      week?: number
      /** ISO instant; a future one renders the tile locked ("Opens Aug 24"). */
      unlockDate?: string
      items?: Item[]
    }

const FIXTURE: Entry[] = [
  { kind: 'divider', slug: 'div-foundations', title: 'Unit 1 — Foundations' },

  {
    kind: 'module',
    slug: 'w1',
    title: 'Intro & Setup',
    description: 'Course logistics, toolchain install, and your first program.',
    week: 1,
    items: [
      { slug: 'w1-syllabus', type: 'lecture', title: 'Syllabus & grading policy', content: pdf('syllabus', 'CS101-syllabus.pdf') },
      { slug: 'w1-deck', type: 'lecture', title: 'Week 1 Lecture Deck', content: deck('Wk01_intro.ppt') },
      {
        slug: 'w1-note',
        type: 'note',
        title: 'Before the first lab',
        content: note('Install Python 3.12 and VS Code before Thursday. If the installer fails on Windows, post in the Week 1 discussion — do not wait until lab.'),
      },
    ],
  },
  {
    kind: 'module',
    slug: 'w2',
    title: 'Lifecycle Data Processing',
    description: 'How raw data becomes model input: cleaning, encoding, splitting.',
    week: 2,
    items: [
      {
        slug: 'w2-main',
        type: 'lecture',
        title: 'Module 3 — Lifecycle Data Processing',
        // Long on purpose: this is the truncation test for the panel's two columns.
        content: pdf('notes', 'Mod03-Lifecycle_dataprocessing_full_annotated_v3_FINAL.pdf'),
      },
      { slug: 'w2-r', type: 'lecture', title: 'Module 3R — Introduction to R', content: pdf('notes', 'Mod03R_intro_to_R.pdf') },
      { slug: 'w2-deck', type: 'lecture', title: 'Week 2 Lecture Deck', content: deck('Wk02_lecture.ppt') },
      { slug: 'w2-vid', type: 'video', title: 'Walkthrough: encoding categoricals', content: video('https://www.youtube.com/watch?v=dQw4w9WgXcQ', 18) },
    ],
  },
  {
    kind: 'module',
    slug: 'w3',
    title: 'K-Nearest Neighbour',
    description: 'Distance metrics, choosing k, and the bias–variance trade-off.',
    week: 3,
    items: [{ slug: 'w3-pdf', type: 'lecture', title: 'KNN from scratch', content: pdf('notes', 'Wk03-knn.pdf') }],
  },

  { kind: 'divider', slug: 'div-modelling', title: 'Unit 2 — Modelling' },

  {
    kind: 'module',
    slug: 'w4',
    title: 'Algorithm Basics',
    description: 'Complexity analysis and how to reason about algorithm cost.',
    week: 4,
    items: [
      { slug: 'w4-pdf', type: 'lecture', title: 'Big-O in practice', content: pdf('notes', 'Wk04-complexity.pdf') },
      { slug: 'w4-deck', type: 'lecture', title: 'Week 4 Lecture Deck', content: deck('Wk04_lecture.ppt') },
    ],
  },
  {
    kind: 'module',
    slug: 'w5',
    title: 'Data Mining in Life Insurance',
    // Long description: the tile clamps to two lines, the panel shows it in full.
    description:
      'An exploration of how predictive modelling transforms underwriting, risk assessment and pricing across the life insurance industry, including the regulatory constraints that shape which features may lawfully be used.',
    week: 5,
    items: [
      { slug: 'w5-div', type: 'section_divider', title: '', content: { label: 'Before class' } },
      { slug: 'w5-read', type: 'lecture', title: 'Underwriting with gradient boosting', content: pdf('notes', 'Wk05-underwriting.pdf') },
      { slug: 'w5-paper', type: 'reference', title: 'Attention Is All You Need', description: 'Skim §3 only.', content: paper('https://arxiv.org/abs/1706.03762', 'arXiv', '1706.03762') },
      { slug: 'w5-div2', type: 'section_divider', title: '', content: { label: 'After class' } },
      { slug: 'w5-deck', type: 'lecture', title: 'Week 5 Lecture Deck', content: deck('Wk05_lecture.ppt') },
      { slug: 'w5-note', type: 'note', title: 'Exam relevance', content: note('The pricing worked example in §4 is fair game for the midterm. The regulatory table is context only.') },
    ],
  },
  {
    kind: 'module',
    slug: 'w6',
    title: 'Model Evaluation',
    description: 'Cross-validation, confusion matrices, ROC and precision–recall.',
    week: 6,
    // No items at all — the "Empty" tile summary and the empty-panel copy.
    items: [],
  },
  {
    kind: 'module',
    slug: 'w7',
    title: 'Clustering Methods',
    description: 'k-means, hierarchical clustering, and evaluating cluster quality.',
    week: 7,
    unlockDate: days(7),
    // Seeded but unreachable: the page never fetches a locked week's items.
    items: [{ slug: 'w7-pdf', type: 'lecture', title: 'k-means walkthrough', content: pdf('notes', 'Wk07-kmeans.pdf') }],
  },
  {
    kind: 'module',
    slug: 'supp',
    // No week_number: the tile has no eyebrow, so titles must still line up.
    title: 'Supplementary Readings',
    description: 'Optional. Useful if you want more depth than lecture allows.',
    items: [
      { slug: 'supp-1', type: 'reference', title: 'The Elements of Statistical Learning', content: paper('https://hastie.su.domains/ElemStatLearn/', 'Stanford', '') },
      { slug: 'supp-2', type: 'reference', title: 'A Few Useful Things to Know About Machine Learning', content: paper('https://doi.org/10.1145/2347736.2347755', 'DOI', '10.1145/2347736.2347755') },
    ],
  },
  {
    kind: 'module',
    slug: 'w9',
    title: 'Final Review',
    description: 'Consolidation session and exam-style practice set.',
    week: 9,
    unlockDate: days(14),
    items: [{ slug: 'w9-pdf', type: 'lecture', title: 'Practice set', content: pdf('notes', 'Wk09-practice.pdf') }],
  },
]

export interface ModuleFixtureResult {
  moduleCount: number
  lockedCount: number
  dividerCount: number
  itemCount: number
}

/** Seeds the fixture above into one section. Callers own resolving/validating the
 *  section (existence, enabledFeatures) — this only writes rows and uploads the PDF. */
export async function seedModuleFixtures(
  supabase: SupabaseClient,
  { sectionId, institutionId }: { sectionId: string; institutionId: string },
): Promise<ModuleFixtureResult> {
  const moduleIds = FIXTURE.filter((e) => e.kind === 'module').map((e) => idFor(sectionId, e.slug))
  const dividerIds = FIXTURE.filter((e) => e.kind === 'divider').map((e) => idFor(sectionId, e.slug))

  // Clear only OUR rows (items cascade from modules), so a re-run replaces this fixture
  // and leaves anything built by hand untouched.
  const [{ error: delMod }, { error: delDiv }] = await Promise.all([
    supabase.from('modules').delete().in('id', moduleIds),
    supabase.from('module_dividers').delete().in('id', dividerIds),
  ])
  if (delMod) throw delMod
  if (delDiv) throw delDiv

  // Append after whatever is already there. Modules and dividers SHARE one position
  // scale — that shared order is what the page and the roadmap both read.
  const [{ data: lastMod }, { data: lastDiv }] = await Promise.all([
    supabase.from('modules').select('position').eq('section_id', sectionId).order('position', { ascending: false }).limit(1),
    supabase.from('module_dividers').select('position').eq('section_id', sectionId).order('position', { ascending: false }).limit(1),
  ])
  const base = Math.max(lastMod?.[0]?.position ?? -1, lastDiv?.[0]?.position ?? -1) + 1

  const moduleRows: Record<string, unknown>[] = []
  const dividerRows: Record<string, unknown>[] = []
  const itemRows: Record<string, unknown>[] = []

  FIXTURE.forEach((entry, i) => {
    const position = base + i
    if (entry.kind === 'divider') {
      dividerRows.push({
        id: idFor(sectionId, entry.slug),
        // module_dividers is tenant-scoped in its own right, unlike modules (which
        // inherit tenancy through section_id).
        institution_id: institutionId,
        section_id: sectionId,
        title: entry.title,
        position,
      })
      return
    }
    moduleRows.push({
      id: idFor(sectionId, entry.slug),
      section_id: sectionId,
      title: entry.title,
      description: entry.description ?? '',
      week_number: entry.week ?? null,
      position,
      is_published: true,
      unlock_date: entry.unlockDate ?? null,
      // Never seeded: private teaching commentary is exactly what the student page's
      // explicit column list exists to keep out of the browser payload.
      instructor_note: '',
    })
    ;(entry.items ?? []).forEach((item, j) => {
      itemRows.push({
        id: idFor(sectionId, item.slug),
        module_id: idFor(sectionId, entry.slug),
        item_type: item.type,
        title: item.title,
        description: item.description ?? '',
        content: item.content,
        position: j,
        is_visible: true,
      })
    })
  })

  // Upload before the items reference them. upsert so re-runs are cheap and so a
  // half-finished earlier run can't leave rows pointing at nothing.
  const [{ error: upSyllabusErr }, { error: upNotesErr }] = await Promise.all([
    supabase.storage
      .from(BUCKET)
      .upload(SYLLABUS_PDF_PATH, SYLLABUS.bytes, { contentType: 'application/pdf', upsert: true }),
    supabase.storage
      .from(BUCKET)
      .upload(LECTURE_NOTES_PDF_PATH, LECTURE_NOTES.bytes, { contentType: 'application/pdf', upsert: true }),
  ])
  if (upSyllabusErr) throw upSyllabusErr
  if (upNotesErr) throw upNotesErr

  const { error: modErr } = await supabase.from('modules').insert(moduleRows)
  if (modErr) throw modErr
  const { error: divErr } = await supabase.from('module_dividers').insert(dividerRows)
  if (divErr) throw divErr
  const { error: itemErr } = await supabase.from('module_items').insert(itemRows)
  if (itemErr) throw itemErr

  return {
    moduleCount: moduleRows.length,
    lockedCount: moduleRows.filter((m) => m.unlock_date).length,
    dividerCount: dividerRows.length,
    itemCount: itemRows.length,
  }
}
