/**
 * AddSectionDialog — modal for adding a section to an existing course.
 *
 * Admin picks a professor, semester, year, and modality. Section code
 * (A, B, C...) is auto-generated by the server action.
 *
 * Type: Client Component
 */
'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { toast } from 'sonner'
import { z } from 'zod'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { SEMESTERS, SEMESTER_LABELS, MODALITIES, MODALITY_LABELS } from '@/lib/validations/course-assignment'
import { assignCourse } from '@/app/(dashboard)/admin/courses/actions'

const addSectionSchema = z.object({
  professor_id: z.string().uuid('Select a professor'),
  section_code: z.string().min(1, 'Section letter is required').max(10, 'Max 10 characters').trim().toUpperCase(),
  semester: z.enum(['fall', 'spring', 'summer', 'winter']),
  year: z.number().int().min(2020).max(2050),
  modality: z.enum(['in_person', 'online', 'hybrid']).optional(),
  max_students: z.number().int().min(1).max(500).optional(),
})

type AddSectionInput = z.infer<typeof addSectionSchema>

interface Professor {
  id: string
  name: string
  email: string
}

interface AddSectionDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  courseId: string
  courseName: string
  professors: Professor[]
}

export function AddSectionDialog({ open, onOpenChange, courseId, courseName, professors }: AddSectionDialogProps) {
  const [isSubmitting, setIsSubmitting] = useState(false)

  const form = useForm<AddSectionInput>({
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    resolver: zodResolver(addSectionSchema) as any,
    defaultValues: {
      professor_id: '',
      section_code: '',
      semester: 'fall',
      year: new Date().getFullYear(),
      modality: 'in_person',
      max_students: 50,
    },
  })

  const onSubmit = async (data: AddSectionInput) => {
    setIsSubmitting(true)
    try {
      const result = await assignCourse({
        course_id: courseId,
        professor_id: data.professor_id,
        section_code: data.section_code,
        semester: data.semester,
        year: data.year,
        modality: data.modality,
        max_students: data.max_students,
      })
      if ('error' in result && result.error) {
        toast.error(result.error)
        return
      }
      toast.success('Section added')
      form.reset()
      onOpenChange(false)
    } catch {
      toast.error('Something went wrong')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle>Add Section</DialogTitle>
          <DialogDescription>
            Create a new section for <span className="font-medium">{courseName}</span>.
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {/* Professor */}
            <FormField
              control={form.control}
              name="professor_id"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Professor *</FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Assign a professor" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {professors.map((p) => (
                        <SelectItem key={p.id} value={p.id}>
                          {p.name} · {p.email}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Section Letter */}
            <FormField
              control={form.control}
              name="section_code"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Section Letter *</FormLabel>
                  <FormControl>
                    <Input placeholder="A, B, C..." maxLength={10} {...field} className="uppercase" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Semester + Year */}
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="semester"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Semester *</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger><SelectValue /></SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {SEMESTERS.map((s) => (
                          <SelectItem key={s} value={s}>{SEMESTER_LABELS[s]}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="year"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Year *</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} onChange={(e) => field.onChange(Number(e.target.value))} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Modality + Capacity */}
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="modality"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Modality</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger><SelectValue /></SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {MODALITIES.map((m) => (
                          <SelectItem key={m} value={m}>{MODALITY_LABELS[m]}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="max_students"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Max Students</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        {...field}
                        value={field.value ?? 50}
                        onChange={(e) => field.onChange(e.target.value ? Number(e.target.value) : 50)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex justify-end gap-3 pt-2">
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={isSubmitting}>
                Cancel
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting ? 'Adding...' : 'Add Section'}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  )
}
