/**
 * C11 — "what should I ask in class?", drafted from the student's own wrong
 * answers and pre-filled into the live classroom's question box (§12.2, §14).
 *
 * The draft is composed HERE, deterministically, from a question they actually
 * got wrong — not generated by the model. Two reasons, and the second is the
 * one that matters:
 *
 *   1. It is going into a form the student will send to their professor under
 *      their own name. A templated sentence built from a real missed question
 *      is something they can verify at a glance; a generated one they'd have to
 *      read carefully to catch a fabricated detail.
 *   2. Provenance. Everything else on the propose path is server-owned — the
 *      route, the plan rows, the ids. A model-authored payload riding the same
 *      channel would be the one exception, and exceptions are what get copied.
 *
 * The student edits it before sending; that is the point of pre-filling rather
 * than posting.
 */

import type { ReviewedQuiz } from './quiz-history'

export interface MissedQuestion {
  quiz: string
  question: string
  yourAnswer: string
  correctAnswer: string
}

export type NoQuestionReason = 'no_live_room' | 'nothing_missed_yet'

export interface ClassQuestionDraft {
  /** The text that lands in the question box. */
  text: string
  /** What it was built from, so the answer can explain itself honestly. */
  from: MissedQuestion
}

/** Question text long enough to be recognisable, short enough that the drafted
 *  sentence stays askable out loud. */
const MAX_QUOTED = 160

/** The most recent question the student got wrong, or null. */
export function mostRecentMiss(quizzes: ReviewedQuiz[]): MissedQuestion | null {
  // `fetchReviewableQuizzes` returns attempts most-recent-first, so the first
  // wrong answer we meet is the freshest one — the thing still on their mind.
  for (const quiz of quizzes) {
    for (const q of quiz.questions) {
      if (q.correct) continue
      if (!q.question.trim()) continue
      return {
        quiz: quiz.quiz,
        question: q.question.trim(),
        yourAnswer: q.yourAnswer,
        correctAnswer: q.correctAnswer,
      }
    }
  }
  return null
}

/**
 * Compose the question. Deliberately plain: it is going in a student's mouth in
 * front of their class, so it stays short, first-person, and free of anything
 * they'd have to defend. It quotes the prompt rather than their wrong answer —
 * "I answered X" in a public question box is a cost with no benefit.
 */
export function draftClassQuestion(miss: MissedQuestion): ClassQuestionDraft {
  const quoted =
    miss.question.length > MAX_QUOTED ? `${miss.question.slice(0, MAX_QUOTED).trimEnd()}…` : miss.question
  return {
    text: `Could you go over this again? On ${miss.quiz} I got "${quoted}" wrong and I'm still not sure why.`,
    from: miss,
  }
}
