-- Retire the pgvector layer (#435, athena-students.md §5 "Part 1 cutover").
--
-- `content_embeddings` + `match_skill_pages` powered exactly one feature: the
-- material-viewer reference rail's topic→page anchors. That rail now matches
-- topics against the Pinecone materials index instead (roadmap-rail-v1,
-- src/lib/pinecone/topic-pages.ts), computed when a material is indexed and
-- stored on `module_items.content.topicPages` — so the read path no longer
-- touches this table at all.
--
-- Why now: the embedding model these vectors were built with,
-- gemini-embedding-001, is past its announced shutdown date. It still answers,
-- but the pipeline that wrote here is best-effort by design, so the day Google
-- turns it off new uploads would silently stop getting anchors and nothing
-- would surface it. Rather than re-embed every row onto a new model to keep a
-- second vector store alive, the second vector store goes: Pinecone is the
-- team's vector database (.claude/rules/vector-db.md) and pgvector was always
-- the odd one out.
--
-- Nothing else reads either object — `src/lib/ai/embeddings.ts` and
-- `roadmapQueries.getTopicPageHits` are deleted in the same commit, and the
-- extraction worker's cleanup job no longer purges rows here.
--
-- The rows are not migrated. They are a derived projection of `module_items`
-- content, and their replacement is regenerated by re-indexing a material —
-- which is also the only way to get anchors under the new scheme.

drop function if exists public.match_skill_pages(uuid[], double precision, integer);

drop table if exists public.content_embeddings;

-- The `vector` extension stays. It is cheap, it is in the `extensions` schema
-- rather than public, and dropping an extension is the kind of change that
-- breaks a restore in a way nobody notices until they need one. No table uses
-- it today; if that is still true in a year, drop it then.
