-- Pre-Class Primers: a short AI-generated audio "advance organizer" per lecture.
--
-- One primer per lecture-type module_item. Before a class, a student can listen
-- to a ~3-4 minute audio that primes them on what the lecture covers (hook →
-- bridge to prior class → key terms → structure preview → guiding questions).
-- The script is generated by Gemini from the lecture's module/deck content and
-- synthesized to mp3 via ElevenLabs TTS.
--
-- Generation model (cloned from Class Insights): a fire-and-forget kick hits an
-- internal secret-gated route; the orchestrator holds an atomic claim on this
-- row (status generating|ready|failed) so concurrent triggers don't double-spend
-- the TTS API. Regeneration is keyed on source_hash — when the lecture's source
-- content changes, the hash differs and the primer is rebuilt on next read.
--
-- Audio lives in the dedicated private `preclass-audio` bucket (created in the
-- sibling migration 20260702142230_preclass_audio_bucket.sql) under
--   <institutionId>/<sectionId>/<moduleItemId>/<sourceHash>.mp3
-- The hash in the path means a regenerate writes a NEW object, so a listener
-- mid-stream on the old signed URL is never cut off. Read/written server-side
-- via the admin client (signed URLs at read time). No storage policies here.

-- ── preclass_primers ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.preclass_primers (
  module_item_id uuid PRIMARY KEY REFERENCES public.module_items(id) ON DELETE CASCADE,
  section_id uuid NOT NULL REFERENCES public.course_sections(id) ON DELETE CASCADE,
  institution_id uuid NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'generating'
    CHECK (status IN ('generating', 'ready', 'failed')),
  -- Whether students can currently see/hear the primer. The professor's per-lecture
  -- toggle flips this WITHOUT deleting the generated audio: disable hides it,
  -- re-enable serves the same file again (a primer is generated once; only an
  -- explicit Regenerate re-generates). Students only ever see is_available rows.
  is_available boolean NOT NULL DEFAULT true,
  script text,
  audio_path text,
  duration_seconds integer,
  -- sha256 of the lecture's source content; drives the Regenerate freshness check.
  source_hash text,
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS SELECT policies filter by section_id (via enrollment/ownership subqueries),
-- so it needs a btree index.
CREATE INDEX IF NOT EXISTS idx_preclass_primers_section ON public.preclass_primers(section_id);

ALTER TABLE public.preclass_primers ENABLE ROW LEVEL SECURITY;

-- ── RLS: preclass_primers ────────────────────────────────────────
-- SELECT-only for clients; ALL writes run through the admin client (service_role
-- bypasses RLS) after the server action verifies enrollment + ownership + that
-- the feature is enabled. There is NO client-side write path, so — exactly like
-- assignment_submissions — these are FOR SELECT, never FOR ALL. A FOR ALL policy
-- would let any enrolled student UPSERT status='ready', audio_path=<anything>
-- straight through PostgREST, bypassing the server checks. Membership predicates
-- transitively scope by institution (a section belongs to exactly one).
-- auth.uid() is wrapped in a scalar subquery so the planner runs it once per
-- query, not once per row (auth_rls_initplan advisor).

CREATE POLICY "Staff can read section primers"
  ON public.preclass_primers FOR SELECT
  USING (
    section_id IN (
      SELECT id FROM public.course_sections WHERE professor_id = (select auth.uid())
    )
    OR section_id IN (
      SELECT section_id FROM public.section_staff
      WHERE staff_id = (select auth.uid()) AND status = 'active' AND ends_at > now()
    )
  );

CREATE POLICY "Enrolled students can read section primers"
  ON public.preclass_primers FOR SELECT
  USING (
    section_id IN (
      SELECT section_id FROM public.enrollments
      WHERE student_id = (select auth.uid()) AND status IN ('enrolled', 'completed', 'active')
    )
  );
