-- ============================================================
-- AI quiz — source citation on quiz questions
-- ============================================================
-- See docs/designs/quizzes/hybrid-extraction-and-citation.md §15 (citations & peek)
-- and §16 (visual questions, quiz uploads).
--
-- When a question is generated by AI, we remember which file + page it was
-- drawn from. The citation powers three things:
--   1. The professor's "Source · p.N" peek chip in the quiz creator (opens
--      the rendered source page, same UX as the AI tutor's citations).
--   2. Visual questions: the same resolution step attaches a cropped image
--      of the cited figure/chart/table to the question (image_path).
--   3. Provenance on ad-hoc quiz uploads: at quiz save, cited upload items
--      get "used by <quiz>" stamped into module_items.content.quizUpload.
--
-- One nullable jsonb column. Null for hand-written questions and for AI
-- questions whose cited source couldn't be verified. Shape (discriminated by
-- `kind`):
--   { "kind": "module_item", "moduleItemId": "<uuid>", "page": 14, "title": "Transformers" }
--   { "kind": "upload",      "filePath": "<sectionId>/quiz-ai-uploads/deck.pdf", "page": 3, "title": "deck.pdf" }
-- `module_item` is the normal kind — ad-hoc dialog uploads are registered as
-- hidden module items and cite by id. `upload` (cite-by-storage-path) is the
-- legacy/fallback shape, still written only when an upload's registration
-- failed and generation fell back to the in-memory parse; the peek endpoint
-- keeps supporting both.
--
-- RLS: unchanged. Adding a column needs no new policy — the existing
-- per-section policies on quiz_questions still gate every row.
-- ============================================================

ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS source_citation jsonb;

COMMENT ON COLUMN quiz_questions.source_citation IS
  'AI-generated questions only: {kind, page, title} + (moduleItemId | filePath) of the source the question was drawn from. Null when hand-written or unverifiable. Drives the professor peek chip, visual-question crop attachment, and quiz-upload usage stamping. kind=upload is the legacy fallback (registration-failed ad-hoc uploads).';
